/**
 * SVG exporter for vector floor plans
 * Generates clean SVG files with layers for walls, doors, windows, labels, and dimensions
 */

/**
 * Export vector floor plans to SVG
 * @param {Object} vectorPlan - Vector plan data from vectorPlanGenerator
 * @param {Object} metadata - Project metadata
 * @returns {string} SVG content
 */
export function exportToSVG(vectorPlan, metadata = {}) {
  const scale = 100; // 1:100 scale (1m = 1cm on paper)
  const pixelsPerMeter = 20; // SVG units per meter for display
  const margin = 50;

  let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
`;

  // Add metadata
  svg += `  <title>${metadata.projectName || 'Architectural Floor Plans'}</title>
  <desc>Generated by ArchitectAI Platform - Scale 1:${scale}</desc>
`;

  vectorPlan.floors.forEach((floor, floorIndex) => {
    const bounds = floor.bounds;
    const width = (bounds.maxX - bounds.minX) * pixelsPerMeter + margin * 2;
    const height = (bounds.maxY - bounds.minY) * pixelsPerMeter + margin * 2;
    const offsetY = floorIndex * (height + 100);

    // Floor group
    svg += `\n  <!-- ${floor.name} -->\n`;
    svg += `  <g id="floor-${floor.level}" transform="translate(0, ${offsetY})">\n`;

    // Background
    svg += `    <rect x="0" y="0" width="${width}" height="${height}" fill="#ffffff" stroke="none"/>\n`;

    // Transform helper
    const tx = (x) => (x - bounds.minX) * pixelsPerMeter + margin;
    const ty = (y) => (bounds.maxY - y) * pixelsPerMeter + margin; // Flip Y

    // Walls layer
    svg += `    <g id="walls-${floor.level}" stroke="#000000" stroke-width="2" fill="none">\n`;
    floor.layers.walls.forEach(wall => {
      const thickness = (wall.thickness || 0.2) * pixelsPerMeter;
      svg += `      <line x1="${tx(wall.x1)}" y1="${ty(wall.y1)}" x2="${tx(wall.x2)}" y2="${ty(wall.y2)}" stroke-width="${thickness}"/>\n`;
    });
    svg += `    </g>\n`;

    // Doors layer
    svg += `    <g id="doors-${floor.level}" stroke="#000000" stroke-width="1" fill="none">\n`;
    floor.layers.doors.forEach(door => {
      const w = door.width * pixelsPerMeter;
      const x = tx(door.x);
      const y = ty(door.y);
      // Draw door as arc
      svg += `      <path d="M ${x - w/2} ${y} L ${x - w/2} ${y - w} A ${w} ${w} 0 0 1 ${x + w/2} ${y}" stroke="#666666" fill="none"/>\n`;
    });
    svg += `    </g>\n`;

    // Windows layer
    svg += `    <g id="windows-${floor.level}" stroke="#0066cc" stroke-width="2" fill="none">\n`;
    floor.layers.windows.forEach(window => {
      const w = window.width * pixelsPerMeter;
      const x = tx(window.x);
      const y = ty(window.y);
      svg += `      <line x1="${x - w/2}" y1="${y}" x2="${x + w/2}" y2="${y}" stroke-width="3"/>\n`;
    });
    svg += `    </g>\n`;

    // Labels layer
    svg += `    <g id="labels-${floor.level}" font-family="Arial, sans-serif" font-size="12" fill="#000000" text-anchor="middle">\n`;
    floor.layers.labels.forEach(label => {
      const x = tx(label.x);
      const y = ty(label.y);
      svg += `      <text x="${x}" y="${y}">${label.text}</text>\n`;
      if (label.area) {
        svg += `      <text x="${x}" y="${y + 15}" font-size="10" fill="#666666">${label.area.toFixed(1)}m²</text>\n`;
      }
    });
    svg += `    </g>\n`;

    // Dimensions layer
    svg += `    <g id="dimensions-${floor.level}" stroke="#ff0000" stroke-width="0.5" fill="none" font-family="Arial" font-size="10" fill="#ff0000">\n`;
    floor.layers.dimensions.forEach(dim => {
      const x1 = tx(dim.x1);
      const y1 = ty(dim.y1);
      const x2 = tx(dim.x2);
      const y2 = ty(dim.y2);
      const midX = (x1 + x2) / 2;
      const midY = (y1 + y2) / 2;

      svg += `      <line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>\n`;
      svg += `      <text x="${midX}" y="${midY - 5}" text-anchor="middle">${dim.label}</text>\n`;
    });
    svg += `    </g>\n`;

    // Title block
    svg += `    <g id="title-${floor.level}" font-family="Arial, sans-serif">\n`;
    svg += `      <text x="${margin}" y="${margin - 20}" font-size="16" font-weight="bold">${floor.name}</text>\n`;
    svg += `      <text x="${margin}" y="${margin - 5}" font-size="10" fill="#666666">Scale 1:${scale} | Elevation: ${floor.elevation.toFixed(2)}m</text>\n`;
    svg += `    </g>\n`;

    // North arrow
    const arrowX = width - margin - 30;
    const arrowY = margin + 30;
    svg += `    <g id="north-arrow-${floor.level}" transform="translate(${arrowX}, ${arrowY})">\n`;
    svg += `      <line x1="0" y1="0" x2="0" y2="-20" stroke="#000000" stroke-width="2" marker-end="url(#arrowhead)"/>\n`;
    svg += `      <text x="5" y="-10" font-size="10" font-weight="bold">N</text>\n`;
    svg += `    </g>\n`;

    // Scale bar
    const scaleBarX = width - margin - 100;
    const scaleBarY = height - margin + 20;
    const scaleBarLength = 5 * pixelsPerMeter; // 5 meters
    svg += `    <g id="scale-bar-${floor.level}">\n`;
    svg += `      <line x1="${scaleBarX}" y1="${scaleBarY}" x2="${scaleBarX + scaleBarLength}" y2="${scaleBarY}" stroke="#000000" stroke-width="2"/>\n`;
    svg += `      <line x1="${scaleBarX}" y1="${scaleBarY - 5}" x2="${scaleBarX}" y2="${scaleBarY + 5}" stroke="#000000" stroke-width="2"/>\n`;
    svg += `      <line x1="${scaleBarX + scaleBarLength}" y1="${scaleBarY - 5}" x2="${scaleBarX + scaleBarLength}" y2="${scaleBarY + 5}" stroke="#000000" stroke-width="2"/>\n`;
    svg += `      <text x="${scaleBarX + scaleBarLength/2}" y="${scaleBarY + 15}" font-size="10" text-anchor="middle">5m</text>\n`;
    svg += `    </g>\n`;

    svg += `  </g>\n`;
  });

  // Arrow marker definition
  svg += `  <defs>
    <marker id="arrowhead" markerWidth="10" markerHeight="10" refX="5" refY="5" orient="auto">
      <polygon points="0 0, 10 5, 0 10" fill="#000000"/>
    </marker>
  </defs>\n`;

  svg += `</svg>`;

  return svg;
}

